function createfigure(X1, Y1, X2, Y2, X3, Y3, X4, xdata1, ydata1, zdata1, cdata1, xdata2, ydata2, zdata2, X5, Y4, YData3, XData3, YData4)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, XDATA1, YDATA1, ZDATA1, CDATA1, XDATA2, YDATA2, ZDATA2, X5, Y4, YDATA3, XDATA3, YDATA4)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  CDATA1:  surface cdata
%  XDATA2:  contour x
%  YDATA2:  contour y
%  ZDATA2:  contour z
%  X5:  vector of x data
%  Y4:  vector of y data
%  YDATA3:  line ydata
%  XDATA3:  line xdata
%  YDATA4:  line ydata

%  Auto-generated by MATLAB on 18-Jun-2018 19:53:03

% Create figure
figure1 = figure('NumberTitle','off','Name','17: ft_topoplotTFR: stat');

% Create axes
axes1 = axes('Visible','off','Parent',figure1,...
    'PlotBoxAspectRatio',[434 342.3 489],...
    'DataAspectRatio',[1 1 1],...
    'CLim',[-4 4]);
hold(axes1,'all');

% Create title
title('xp=0.015968','FontSize',8);

% Create plot
plot(X1,Y1,'LineWidth',2,'Color',[0 0 0]);

% Create plot
plot(X2,Y2,'LineWidth',2,'Color',[0 0 0]);

% Create plot
plot(X3,Y3,'LineWidth',2,'Color',[0 0 0]);

% Create plot
plot(X4,Y3,'LineWidth',2,'Color',[0 0 0]);

% Create surf
surf(xdata1,ydata1,zdata1,cdata1,'Parent',axes1,'EdgeColor','none');

% Create contour
contour(xdata2,ydata2,zdata2,'LineColor',[0 0 0],...
    'LevelList',[-0.264260948262602 0.323575053698049 0.9114110556587 1.49924705761935 2.08708305958 2.67491906154065]);

% Create plot
plot(X5,Y4,'Marker','x','LineStyle','none','Color',[0 0 0]);

% Create line
line(X1,Y1,'Parent',axes1,'LineWidth',2);

% Create line
line(X2,Y2,'Parent',axes1,'LineWidth',2);

% Create line
line(X3,YData3,'Parent',axes1,'LineWidth',2);

% Create line
line(X4,YData3,'Parent',axes1,'LineWidth',2);

% Create line
line(XData3,YData4,'Parent',axes1,'LineWidth',1.5,'LineStyle',':');

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information

% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information

% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information

% uimenu(...);

