%griddedInterpolant   Interpolant for gridded data
%   F = griddedInterpolant(x,v) creates an interpolant F from vectors x and v, 
%   where x represents a set of points and v the corresponding values.
%   F can compute interpolated values vq at a vector of query locations xq 
%   using vq = F(xq).
% 
%   F = griddedInterpolant(X1,X2,...,Xn,V) specifies the grid as n n-D arrays 
%   Xi created from grid vectors xig by [X1,X2,...,Xn]=NDGRID(x1g,x2g,...,xng),
%   where size(Xi) is size(V).
% 
%   F = griddedInterpolant(V) uses a default grid formed by the grid vectors  
%   xig = 1:size(V,i) to interpolate the array of values V. 
% 
%   F = griddedInterpolant({x1g,x2g,...,xng},V) specifies the grid in compact 
%   form in terms of grid vectors xig, where length(xig) is size(V,i).
%
%   F = griddedInterpolant(...,METHOD) specifies the interpolation technique. 
%   METHOD is one of the following:
%     'nearest' - nearest neighbor interpolation
%     'linear'  - linear, bilinear, trilinear,... interpolation (default)
%     'spline'  - spline interpolation
%     'pchip'   - shape-preserving piecewise cubic interpolation (1D only)
%     'cubic'   - cubic, bicubic, tricubic,... for uniformly spaced data only
%               
%   The interpolant F may be evaluated on scattered or gridded query locations:
%   Vq = F(Xq) evaluates F at the query locations Xq to produce the
%   corresponding values Vq. Xq is a matrix of size m-by-n,
%   representing m points scattered in n-D space. Vq is m-by-1.
% 
%   Vq = F(x1q,x2q,...,xnq) specifies the query locations xiq as column vectors
%   of length m representing m points scattered in n-D space. Vq is m-by-1.
% 
%   Vq = F(X1q,X2q,...,Xnq) specifies the query locations as n n-D arrays Xiq
%   of equal size specifying the full grid. Vq is the same size as Xiq.
%
%   Vq = F({x1gq,x2gq,...,xngq}) specifies the query locations as a grid 
%   formed by the grid vectors xigq. Vq is the size of grid defined by xigq, 
%   length(x1gq)-by-length(x2gq)-by-...by-length(xngq).
% 
%  
%   griddedInterpolant properties:
%     GridVectors  - A cell array containing the grid vectors
%     Values       - An array of values associated with each gridpoint
%     Method       - The method used to interpolate the data
% 
%   Example: Interpolate to refine a grid-based sampling 
%     [X1, X2] = ndgrid(1:10,1:10);
%     V = X1.^2 + X2.^2;
%     F = griddedInterpolant(X1,X2,V, 'cubic');
%     [X1q, X2q] = ndgrid(1:0.5:10,1:0.5:10);
%     Vq = F(X1q,X2q);
%     mesh(X1q,X2q,Vq);
%
%    See also  griddedInterpolantDemo, ndgrid, interp1, interp2, interp3, interpn.

%   Copyright 2011 The MathWorks, Inc.
%   $Revision: 1.1.6.1.2.1 $
%   Built-in function.

%{
properties
    %GridVectors - A cell array containing the vectors that define the grid.
    %    An n-D interpolant contains n grid vectors. The grid
    %    vectors are a compact representation of the grid. The fully
    %    expanded grid can be generated by passing the grid vectors into
    %    ndgrid as follows;
    %    [X1, X2, X3, . . . Xn] = ndgrid(GridVectors{:});
    GridVectors;    

    %Values - Defines the value associated with each grid point
    %    The array of values has the same dimensions as the underlying
    %    grid that is implicitly defined by GridVectors.
    Values;

    %Method - Defines the method used to interpolate the data
    %    The Method is one of the following; 
    %     'nearest' - nearest neighbor interpolation
    %     'linear'  - linear, bilinear, trilinear,... interpolation (default)
    %     'spline'  - spline interpolation
    %     'pchip'   - shape-preserving piecewise cubic interpolation (1D only)
    %     'cubic'   - cubic, bicubic, tricubic,... for uniformly spaced data only
    Method;
end
%}

